#' Example Acoustic Telemetry Detection Data from Hamilton Harbour
#'
#' @description A subsampled dataset containing the first 100,000 acoustic
#' telemetry detections from Hamilton Harbour. This data is used for
#' demonstration and testing of the network analysis and detection processing
#' functions. Data follows GLATOS format conventions.
#'
#' @format A dataframe with 100,000 detection records including:
#' \describe{
#'   \item{animal_id}{Fish identification code}
#'   \item{station_no}{Receiver station identifier}
#'   \item{detection_timestamp_est}{Detection timestamp (EST)}
#'   \item{deploy_lat}{Latitude of receiver deployment}
#'   \item{deploy_long}{Longitude of receiver deployment}
#'   \item{date}{Detection date}
#'   \item{transmitter_codespace}{Transmitter manufacturer code}
#'   \item{transmitter_id}{Transmitter identification number}
#'   \item{length}{Fish length (mm)}
#'   \item{...}{Additional detection metadata columns}
#' }
#'
#' @source Hamilton Harbour acoustic telemetry study, Fish Ecology Science Lab (FESL)
"example_data_raw_dets"



#' Hamilton Harbour Shoreline Shapefile (WGS84)
#'
#' @description An sf spatial object containing the shoreline boundary of
#' Hamilton Harbour in WGS84 coordinate reference system (EPSG:4326). Used for
#' geographic context in network plots and spatial visualizations.
#'
#' @format An sf object with MULTIPOLYGON geometry representing the
#' Hamilton Harbour shoreline boundary.
#'
#' @source Hamilton Harbour GIS data, Fish Ecology Science Lab (FESL)
"shapefile_HH_WGS84"



#' Hamilton Harbour Base Map
#'
#' @description A ggmap raster object containing a base map of Hamilton Harbour
#' for use as a background in spatial visualizations and plots.
#'
#' @format A ggmap raster object
#'
#' @source Hamilton Harbour mapping data, Fish Ecology Science Lab (FESL)
"basemap_HH"



#' Von Bertalanffy Growth Parameters by Species
#'
#' @description A lookup table of von Bertalanffy growth parameters for
#' Hamilton Harbour fish species. Used by \code{\link{calculate_age_at_tagging}}
#' and \code{\link{project_growth_forward}} to estimate age and projected fork
#' length without requiring users to supply parameters manually.
#'
#' @format A dataframe with one row per species population:
#' \describe{
#'   \item{species_common}{Common name (matches \code{atel$animals$species_common})}
#'   \item{species_scientific}{Scientific name}
#'   \item{linf}{Asymptotic fork length (mm)}
#'   \item{k}{Growth coefficient}
#'   \item{t0}{Theoretical age at fork length = 0 (years)}
#'   \item{fl_units}{Units for fork length and Linf (always "mm")}
#'   \item{population}{Population or lake context for the parameter estimate}
#'   \item{citation}{Short author-year citation}
#'   \item{doi}{DOI link to source publication}
#' }
#'
#' @details
#' Currently populated for Walleye (Hamilton Harbour, Lake Ontario).
#' Additional species can be added to \code{data-raw/vb_growth_params.csv}
#' and the dataset regenerated by running \code{data-raw/format_growth_params.R}.
#'
#' @source
#' Brooks JL, Lédée EJI, Larocque SM, et al. (2025) The influence of thermal
#' and hypoxia induced habitat compression on walleye (\emph{Sander vitreus})
#' movements in a temperate lake. Mov Ecol 13:1.
#' \doi{10.1186/s40462-024-00505-6}
"vb_growth_params"



#' Fish Morphology Regression Parameters by Species
#'
#' @description Species-specific regression parameters relating fork length,
#' body width, and body mass for nine Hamilton Harbour fish species. Used by
#' \code{\link{predict_morphology}} to predict body dimensions from fork length.
#'
#' @format A dataframe with one row per species-relationship combination:
#' \describe{
#'   \item{species_common}{Common name}
#'   \item{relationship}{Morphometric relationship key. One of:
#'     \code{"width_fl"} (Width ~ FL, linear),
#'     \code{"mass_fl"} (Mass ~ FL, power law),
#'     \code{"mass_width"} (Mass ~ Width, power law),
#'     \code{"log_width_fl"} (log(Width) ~ log(FL), log-linear),
#'     \code{"width_mass"} (Width ~ Mass, power law).}
#'   \item{n}{Sample size used to fit the model}
#'   \item{intercept_a}{Regression intercept (linear) or scale coefficient (power law)}
#'   \item{slope_b}{Regression slope (linear) or exponent (power law)}
#'   \item{r_squared}{Coefficient of determination}
#'   \item{equation}{Human-readable equation string}
#' }
#'
#' @details
#' Species covered: Brown Bullhead, Gizzard Shad, Goldfish, Largemouth Bass,
#' Rock Bass, Rudd, Walleye, White Perch, Yellow Perch.
#'
#' @source
#' Reddick D, Rizzuto M, Bzonek P, Turner K, Croft-White M, Midwood J.
#' Fish Morphology Characterization — Hamilton Harbour, Lake Ontario. FESL/DFO.
"morphology_params"
